### ISSUE TITLE
Clarification on Phase Center Corrections

### ISSUE THREAD

**Issue by derekpickell** [kristinemlarson/gnssrefl#41]
Hello! I haven’t had much luck in the documentation or papers in determining how phase center variations across multiple bands are or aren’t accounted for with this technique. (1) For example, for a given satellite arc, would we see two different RH estimates for the L1 and L2 bands, each producing a RH relative to the mean phase center of its given frequency? And (perhaps a harder question to answer): how much does the variability in electric phase center as a satellite rises and sets affect GNSS-IR, and are there ways we can preemptively apply antenna corrections such that all RHs are relative to the antenna reference point? Hopefully this makes sense… thank you for the clarification/support!!

**Comment by kristinemlarson** [comment]
So first off, please accept my apology for taking so long to answer. What you say is correct - there will be two RH values for two distinct frequencies. They might be small, but they won't be exactly zero. What does this depend on? To first order it depends on the kind of antenna being used - and that is not surprising because geodesy has known a long time that we need to correct for mean phase center offsets AND phase center variations when using GPS (and now GNSS). Why doesn't gnssrefl remove these offsets? The main reason is that I do not want to remove them unless I am absolutely sure that what we are doing is (1) correct and (2) do it in a way that it is transparent.  Unfortunately we cannot just use the phase center offsets used in geodesy.  They help - but are not 100% of the problem.  For snow and soil moisture it just isn't much of an issue. The main people who want to know about the "true" RH want to measure water levels in ITRF. And this comes to the second reason there are "frequency biases." They depend on the surface!  This means the frequency biases between GPS L1 and L2, for example, are different for snow than they are for sea water. And sea water biases are different than biases for fresh water.  It all depends on the dielectric constant of your surface.  Right now the only place that frequency biases are removed is in the subdaily module. And even there, we level everything to GPS L1.  I think the best thing to do is start a place on the official documentation where this issue is discussed openly.  We are going to make a change to the code this year that allows for fixing the biases, but the codes has to be transparent - and we have to have a database that keeps track of which kind of antenna you were using before we remove biases. If we don't do that, things will become chaotic. So stay tuned.
